server:
  port: 8081

spring:
  data:
    mongodb:
      host: k6b104.p.ssafy.io
      port: 27017
      database: chat
      username: root
      password: woonana123@
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
